Repository dr5hn/countries-states-cities-database, pull requests merged in 2024-10, with the labels that each got.

#865 Update regions.json Americas 'fa' translation
  regions.json
Labels: size:XS, lgtm

#866 Update countries.json Add Kosovo 'fa' translation
  countries.json
Labels: hacktoberfest-accepted, size:XS, lgtm

#851 Update countries.json
  countries.json
Labels: enhancement, size:L, lgtm

#898 Update README.md
  README.md
Labels: size:XS
