Repository dr5hn/countries-states-cities-database, pull requests merged in 2025-03, with the labels that each got.

#957 fix: JSON export region_id type consistency
  bin/Commands/ExportJson.php
Labels: bug, exports, size:XS, lgtm

#963 feat: add if exists flag in postgresql
  .github/workflows/export.yml
Labels: enhancement, size:S

#964 fix: #951 INSERT conflicts with FOREIGN KEY
  bin/Commands/ExportSqlServer.php
Labels: bug, size:S

#967 MongoDB
  .github/workflows/export.yml
  README.md
  bin/Commands/ExportMongoDB.php
Labels: size:L

#990 Update README.md
  README.md
Labels: size:XS

#999 Fix: optimize prisma seeder to reduce DB queries and improve performance
  prisma/seed.ts
Labels: enhancement, size:L, lgtm
